import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Figtree } from "next/font/google";
import { Nav } from "./_components/Nav";
import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { Footer } from "./_components/Footer";
import { CookieBanner } from "./_components/CookieBanner";
import { GoogleTagManager } from '@next/third-parties/google';
import { Toaster } from "sonner";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Foncior",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" suppressHydrationWarning className={cn(geist.variable, "font-sans", figtree.variable)}>
      <GoogleTagManager gtmId="GTM-PT5JGZ7N" />
      <body>
        <Nav/>
        <CookieBanner/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer />
        <Toaster richColors />
      </body>
    </html>
  );
}
