import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Figtree } from "next/font/google";
import { Nav } from "./_components/Nav";
import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { Footer } from "./_components/Footer";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn(geist.variable, "font-sans", figtree.variable)}>
      <body>
        <Nav/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer/>
      </body>
    </html>
  );
}
