import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Figtree } from "next/font/google";
import { Nav } from "./_components/Nav";
import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import { Footer } from "./_components/Footer";
import { CookieBanner } from "./_components/CookieBanner";
import { Toaster } from "sonner";
import Script from "next/script";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Foncior",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" suppressHydrationWarning className={cn(geist.variable, "font-sans", figtree.variable)}>
      <body>
        <Nav/>
        <CookieBanner/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer />
        <Toaster richColors />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-Z88QVP531B"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-Z88QVP531B');
          `}
        </Script>
      </body>
    </html>
  );
}
